version: 1.0
stages:
  - clone
  - build
  - push
  - scan

steps:
  clone:
    title: Cloning repository...
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    stage: clone

  build:
    title: Building Docker image..
    type: build
    image_name: ${{CF_REPO_NAME}}
    working_directory: ${{clone}}
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    dockerfile: Dockerfile
    stage: build

  push:
    title: Pushing Docker image...
    type: push
    candidate: ${{build}}
    registry: gcr
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    stage: push

  PrismaCloudImageScan:
    type: codefreshdemo/prisma-cloud
    arguments:
      IMAGE_NAME: codefresh-sa/${{CF_REPO_NAME}}
      IMAGE_TAG: ${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
      PC_HOSTNAME: ${{PC_HOSTNAME}}
      PC_PORT: ${{PC_PORT}}
      PC_USERNAME: ${{PC_USERNAME}}
      PC_PASSWORD: ${{PC_PASSWORD}}
      PC_PROTOCOL: ${{PC_PROTOCOL}}
      REGISTRY: gcr.io
    stage: scan
